version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: banana-image-backend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Netvine123
      - DB_NAME=banana_image_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=dev_jwt_secret_key
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    depends_on:
      - mysql
      - redis
    networks:
      - banana-network

  mysql:
    image: mysql:8.0
    container_name: banana-mysql-dev
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Netvine123
      - MYSQL_DATABASE=banana_image_db
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - banana-network

  redis:
    image: redis:7-alpine
    container_name: banana-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - banana-network

volumes:
  mysql_dev_data:
  redis_dev_data:
  uploads_data:

networks:
  banana-network:
    driver: bridge